version: 2.1
orbs:
  python: circleci/python@2
jobs:
  test-python:
    docker:
      - image: cimg/python:3.8-node
    steps:
      - checkout
      - run:
          name: Set up virtual environment
          command: python -m venv ~/.venv
      - run:
          name: Activate venv and upgrade pip
          command: |
            source ~/.venv/bin/activate
            pip install --upgrade pip
      - run:
          name: Install dependencies
          command: |
            source ~/.venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Install pytest
          command: |
            source ~/.venv/bin/activate
            pip install pytest
      - run:
          name: Run tests
          command: |
            source ~/.venv/bin/activate
            pytest --junitxml=junit.xml || ((($? == 5)) && echo 'Did not find any tests to run.')
      - store_test_results:
          path: junit.xml
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'
      - run:
          name: found github actions config
          command: ':'
workflows:
  build-and-test:
    jobs:
      - test-python
    # - deploy:
    #     requires:
    #       - test-python
